## csv파일 불러오기

In [1]:
import pandas as pd

In [19]:
df = pd.read_csv('./transfermark50.csv')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   number    50 non-null     int64
 1   name      50 non-null     object
 2   position  50 non-null     object
 3   age       50 non-null     int64
 4   nation    50 non-null     object
 5   team      50 non-null     object
 6   value     50 non-null     object
dtypes: int64(2), object(5)
memory usage: 2.9+ KB

In [6]:
df.head()

,number,name,position,age,nation,team,value
0,1,Erling Haaland,Centre-Forward,23,Norway,Manchester City,€180.00m
1,2,Kylian Mbappé,Centre-Forward,24,France,Paris Saint-Germain,€180.00m
2,3,Jude Bellingham,Central Midfield,20,England,Real Madrid,€150.00m
3,4,Vinicius Junior,Left Winger,23,Brazil,Real Madrid,€150.00m
4,5,Bukayo Saka,Right Winger,22,England,Arsenal FC,€120.00m

In [20]:
df['value'] = df['value'].str.replace('€','')
df['value'] = df['value'].str.replace('m','').astype(float)
df

,number,name,position,age,nation,team,value
0,1,Erling Haaland,Centre-Forward,23,Norway,Manchester City,180.0
1,2,Kylian Mbappé,Centre-Forward,24,France,Paris Saint-Germain,180.0
2,3,Jude Bellingham,Central Midfield,20,England,Real Madrid,150.0
3,4,Vinicius Junior,Left Winger,23,Brazil,Real Madrid,150.0
4,5,Bukayo Saka,Right Winger,22,England,Arsenal FC,120.0
5,6,Victor Osimhen,Centre-Forward,24,Nigeria,SSC Napoli,120.0
6,7,Jamal Musiala,Attacking Midfield,20,Germany,Bayern Munich,110.0
7,8,Phil Foden,Left Winger,23,England,Manchester City,110.0
8,9,Harry Kane,Centre-Forward,30,England,Bayern Munich,110.0
9,10,Pedri,Central Midfield,20,Spain,FC Barcelona,100.0
10,11,Rodrygo,Right Winger,22,Brazil,Real Madrid,100.0
11,12,Lautaro Martínez,Centre-Forward,26,Argentina,Inter Milan,100.0
12,13,Federico Valverde,Central Midfield,25,Uruguay,Real Madrid,100.0
13,14,Declan Rice,Defensive Midfield,24,England,Arsenal FC,100.0
14,15,Rodri,Defensive Midfield,27,Spain,Manchester City,100.0
15,16,Moisés Caicedo,Defensive Midfield,22,Ecuador,Chelsea FC,90.0
16,17,Gavi,Central Midfield,19,Spain,FC Barcelona,90.0
17,18,Eduardo Camavinga,Central Midfield,20,France,Real Madrid,90.0
18,19,Aurélien Tchouaméni,Defensive Midfield,23,France,Real Madrid,90.0
19,20,Rafael Leão,Left Winger,24,Portugal,AC Milan,90.0
20,21,Frenkie de Jong,Central Midfield,26,Netherlands,FC Barcelona,90.0
21,22,Martin Ødegaard,Attacking Midfield,24,Norway,Arsenal FC,90.0
22,23,Florian Wirtz,Attacking Midfield,20,Germany,Bayer 04 Leverkusen,85.0
23,24,Bruno Guimarães,Defensive Midfield,25,Brazil,Newcastle United,85.0
24,25,Khvicha Kvaratskhelia,Left Winger,22,Georgia,SSC Napoli,85.0
25,26,Gabriel Martinelli,Left Winger,22,Brazil,Arsenal FC,80.0
26,27,Enzo Fernández,Central Midfield,22,Argentina,Chelsea FC,80.0
27,28,Julián Álvarez,Centre-Forward,23,Argentina,Manchester City,80.0
28,29,Randal Kolo Muani,Centre-Forward,24,France,Paris Saint-Germain,80.0
29,30,Josko Gvardiol,Centre-Back,21,Croatia,Manchester City,80.0
30,31,Christopher Nkunku,Attacking Midfield,25,France,Chelsea FC,80.0
31,32,Rúben Dias,Centre-Back,26,Portugal,Manchester City,80.0
32,33,Bernardo Silva,Attacking Midfield,29,Portugal,Manchester City,80.0
33,34,Luis Díaz,Left Winger,26,Colombia,Liverpool FC,75.0
34,35,Gabriel Jesus,Centre-Forward,26,Brazil,Arsenal FC,75.0
35,36,Marcus Rashford,Left Winger,26,England,Manchester United,75.0
36,37,Nicolò Barella,Central Midfield,26,Italy,Inter Milan,75.0
37,38,Bruno Fernandes,Attacking Midfield,29,Portugal,Manchester United,75.0
38,39,Jack Grealish,Left Winger,28,England,Manchester City,75.0
39,40,Leroy Sané,Right Winger,27,Germany,Bayern Munich,75.0
40,41,Joshua Kimmich,Defensive Midfield,28,Germany,Bayern Munich,75.0
41,42,Xavi Simons,Right Winger,20,Netherlands,RB Leipzig,70.0
42,43,William Saliba,Centre-Back,22,France,Arsenal FC,70.0
43,44,Ronald Araújo,Centre-Back,24,Uruguay,FC Barcelona,70.0
44,45,Dominik Szoboszlai,Central Midfield,23,Hungary,Liverpool FC,70.0
45,46,Alphonso Davies,Left-Back,23,Canada,Bayern Munich,70.0
46,47,Éder Militão,Centre-Back,25,Brazil,Real Madrid,70.0
47,48,Dušan Vlahović,Centre-Forward,23,Serbia,Juventus FC,70.0
48,49,Alexander Isak,Centre-Forward,24,Sweden,Newcastle United,70.0
49,50,Matthijs de Ligt,Centre-Back,24,Netherlands,Bayern Munich,70.0

In [23]:
df['시장가치(억)'] = df['value']*13

In [25]:
df.head()

,number,name,position,age,nation,team,value,시장가치(억)
0,1,Erling Haaland,Centre-Forward,23,Norway,Manchester City,180.0,2340.0
1,2,Kylian Mbappé,Centre-Forward,24,France,Paris Saint-Germain,180.0,2340.0
2,3,Jude Bellingham,Central Midfield,20,England,Real Madrid,150.0,1950.0
3,4,Vinicius Junior,Left Winger,23,Brazil,Real Madrid,150.0,1950.0
4,5,Bukayo Saka,Right Winger,22,England,Arsenal FC,120.0,1560.0

In [27]:
df.drop(columns=['value'], inplace=True)

In [28]:
df.head()

,number,name,position,age,nation,team,시장가치(억)
0,1,Erling Haaland,Centre-Forward,23,Norway,Manchester City,2340.0
1,2,Kylian Mbappé,Centre-Forward,24,France,Paris Saint-Germain,2340.0
2,3,Jude Bellingham,Central Midfield,20,England,Real Madrid,1950.0
3,4,Vinicius Junior,Left Winger,23,Brazil,Real Madrid,1950.0
4,5,Bukayo Saka,Right Winger,22,England,Arsenal FC,1560.0

# DataFrame 통계분석과 groupby()

In [29]:
# 숫자형 데이터에 대한 통계
df.describe()

         number        age      시장가치(억)
count  50.00000  50.000000    50.000000
mean   25.50000  23.880000  1192.100000
std    14.57738   2.607994   338.033162
min     1.00000  19.000000   910.000000
25%    13.25000  22.000000   975.000000
50%    25.50000  24.000000  1072.500000
75%    37.75000  26.000000  1300.000000
max    50.00000  30.000000  2340.000000

In [32]:
# 컬럼 이름 바꾸고 저장하기 :'team'을 'club'으로 바꾸기 위해 cheat sheet에서 검색 
df.rename(columns = {'team':'club'}, inplace=True)

In [33]:
c = df.groupby("club")
c.sum()

,number,name,position,age,nation,시장가치(억)
club,,,,,,
AC Milan,20,Rafael Leão,Left Winger,24,Portugal,1170.0
Arsenal FC,145,Bukayo SakaDeclan RiceMartin ØdegaardGabriel M...,Right WingerDefensive MidfieldAttacking Midfie...,140,EnglandEnglandNorwayBrazilBrazilFrance,6955.0
Bayer 04 Leverkusen,23,Florian Wirtz,Attacking Midfield,20,Germany,1105.0
Bayern Munich,193,Jamal MusialaHarry KaneLeroy SanéJoshua Kimmic...,Attacking MidfieldCentre-ForwardRight WingerDe...,152,GermanyEnglandGermanyGermanyCanadaNetherlands,6630.0
Chelsea FC,74,Moisés CaicedoEnzo FernándezChristopher Nkunku,Defensive MidfieldCentral MidfieldAttacking Mi...,69,EcuadorArgentinaFrance,3250.0
FC Barcelona,92,PedriGaviFrenkie de JongRonald Araújo,Central MidfieldCentral MidfieldCentral Midfie...,89,SpainSpainNetherlandsUruguay,4550.0
Inter Milan,49,Lautaro MartínezNicolò Barella,Centre-ForwardCentral Midfield,52,ArgentinaItaly,2275.0
Juventus FC,48,Dušan Vlahović,Centre-Forward,23,Serbia,910.0
Liverpool FC,79,Luis DíazDominik Szoboszlai,Left WingerCentral Midfield,49,ColombiaHungary,1885.0
Manchester City,186,Erling HaalandPhil FodenRodriJulián ÁlvarezJos...,Centre-ForwardLeft WingerDefensive MidfieldCen...,200,NorwayEnglandSpainArgentinaCroatiaPortugalPort...,10205.0
Manchester United,74,Marcus RashfordBruno Fernandes,Left WingerAttacking Midfield,55,EnglandPortugal,1950.0
Newcastle United,73,Bruno GuimarãesAlexander Isak,Defensive MidfieldCentre-Forward,49,BrazilSweden,2015.0
Paris Saint-Germain,31,Kylian MbappéRandal Kolo Muani,Centre-ForwardCentre-Forward,48,FranceFrance,3380.0
RB Leipzig,42,Xavi Simons,Right Winger,20,Netherlands,910.0
Real Madrid,115,Jude BellinghamVinicius JuniorRodrygoFederico ...,Central MidfieldLeft WingerRight WingerCentral...,158,EnglandBrazilBrazilUruguayFranceFranceBrazil,9750.0
SSC Napoli,31,Victor OsimhenKhvicha Kvaratskhelia,Centre-ForwardLeft Winger,46,NigeriaGeorgia,2665.0